name: Automatic Rebase
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  autorebase:
    name: Rebase
    runs-on: ubuntu-latest

    steps:
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
