name: Automatic Rebase
on:
  pull_request:
    types: [labeled]
jobs:
  autorebase:
    if: ${{ github.event.label.name == 'auto-rebase' }}
    name: Rebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
